name: Testing
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          python -m pip install -r requirements.txt
          python wag.py -yaml myapp.yaml -app title "My Phonebook App"
      - name: Create a schema
        run: |
          python wag.py -yaml myapp.yaml -schema "The Phonebook" -fields name notes "Phone Number" "Email Address" dob "Contact Type"
      - name: Change a field type
        run: |
          python wag.py -yaml myapp.yaml -schema "The Phonebook" -f notes type textarea
      - name: Change field on_list
        run: |
          python wag.py -yaml myapp.yaml -schema "The Phonebook" -f notes on_list false
      - name: Change field required
        run: |
          python wag.py -yaml myapp.yaml -schema "The Phonebook" -f name required True
      - name: Change field helptext
        run: |
          python wag.py -yaml myapp.yaml -schema "The Phonebook" -f dob helptext "Use the format as YYYY-MM-DD"
      - name: Change field type dropdown
        run: |
          python wag.py -yaml myapp.yaml -schema "The Phonebook" -f "Contact Type" type dropdown
      - name: Change field options
        run: |
          python wag.py -yaml myapp.yaml -schema "The Phonebook" -f "Contact Type" options Supplier Customer
      - name: Create new schema
        run: |
          python wag.py -yaml myapp.yaml -schema "Engagements" -fields Contact Company Enquiry Date
      - name: Change field type engageme
        run: |
          python wag.py -yaml myapp.yaml -schema "Engagements" -f Contact type lookup
      - name: Change field options
        run: |
          python wag.py -yaml myapp.yaml -schema "Engagements" -f Contact options the_phonebook name contact_type
      - name: Generate the output
        run: |
          python wag.py -yaml myapp.yaml -template php -output /tmp
